package client

/*
import (
	"encoding/json"
	"fmt"
)
*/

///////////////////| With the current state of API and API documentation, this doesn't seem like a solvable problem... |////////////////////////

type Settings struct {
	Notifications      *NotificationSettings `json:"notifications,omitempty"`
	FilterNSFW         bool                  `json:"filterNSFW,omitempty"`
	ShowFollowerCount  bool                  `json:"showFollowerCount,omitempty"`
	HideImagesInFeed   bool                  `json:"hideImagesInFeed,omitempty"`
	HideAudioInFeed    bool                  `json:"hideAudioInFeed,omitempty"`
	AutoWatchOnReply   bool                  `json:"autoWatchOnReply,omitempty"`
	KeyboardBindings   map[string]string     `json:"keyboardBindings,omitempty"`
	KeyboardPreset     string                `json:"keyboardPreset,omitempty"`
	IconTheme          string                `json:"iconTheme,omitempty"`
	FollowedTopics     []string              `json:"followedTopics,omitempty"`
	MutedTopics        []string              `json:"mutedTopics,omitempty"`
	ImagePixelSize     int                   `json:"imagePixelSize,omitempty"`
	TimeDisplayFormat  string                `json:"timeDisplayFormat,omitempty"`
	UseLegacyMenuOrder bool                  `json:"useLegacyMenuOrder,omitempty"`
	DefaultPublicPost  bool                  `json:"defaultPublicPost,omitempty"`
}

type NotificationSettings struct {
	Bookmark         bool `json:"bookmark"`
	Reply            bool `json:"reply"`
	ThreadReply      bool `json:"thread_reply"`
	NewFollower      bool `json:"new_follower"`
	Unfollowed       bool `json:"unfollowed"`
	NewPostFollowing bool `json:"new_post_following"`
	NewPostFriend    bool `json:"new_post_friend"`
	Poke             bool `json:"poke"`
	ChatMention      bool `json:"chat_mention"`
	DmMessage        bool `json:"dm_message"`
}

type AutoGenerated struct {
	Data struct {
		NotificationSettings `json:"notifications"`
		ShowFollowerCount    bool          `json:"showFollowerCount"`
		IconTheme            string        `json:"iconTheme"`
		FollowedTopics       []interface{} `json:"followedTopics"`
		HideAudioInFeed      bool          `json:"hideAudioInFeed"`
		MutedTopics          []interface{} `json:"mutedTopics"`
		ImagePixelSize       string        `json:"imagePixelSize"`
		TimeDisplayFormat    string        `json:"timeDisplayFormat"`
		CustomTheme          interface{}   `json:"custom_theme"`
		FilterNSFW           bool          `json:"filterNSFW"`
	} `json:"data"`
}
